spring.profiles.active=dev
#to switch between different properties but if you want to specify while making package or ja file then just to pass
#all the test cases while making the jar for prod with dev with this command mvn clean package -Pprod then
#write that java -jar myapp.jar --spring.profiles.active=prod so test will run against test db and then run jar in
#prod to prevent all db fake entry

external.api.base-url=https://api.example.com
external.api.key=API_KEY
spring.data.redis.host=localhost
spring.data.redis.port=6379
