spring.profiles.active=dev
#to switch between different properties but if you want to specify while making package or ja file then just to pass
#all the test cases while making the jar for prod with dev with this command mvn clean package -Pprod then
#write that java -jar myapp.jar --spring.profiles.active=prod so test will run in test db and then run jar in prod to prevent all db fake entry
